name: firebase-deploy

on: [push, pull_request]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn
        
      - name: Install quasar
        run: yarn global add @quasar/cli

      - name: Generate
      - run: GOOGLE_ANALYTICS_ID=${{ secrets.GOOGLE_ANALYTICS_ID }} quasar build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOMATODO }}
          channelId: live
          projectId: tomatodo
